"""Shared runtime constants for the research pipeline."""

from __future__ import annotations

STOP_MAX_ROUNDS = "MAX_ROUNDS"
STOP_NO_IMPROVEMENT = "NO_IMPROVEMENT"
STOP_OLLAMA_TIMEOUT = "OLLAMA_TIMEOUT"
STOP_PROMPT_TOO_LARGE = "PROMPT_TOO_LARGE"
STOP_INVALID_SCORE = "INVALID_SCORE"
STOP_EXCEPTION = "EXCEPTION"
STOP_MANUAL_INTERRUPT = "MANUAL_INTERRUPT"
STOP_USER_REQUESTED = "USER_STOP_REQUESTED"
STOP_CLOUD_DAILY_QUOTA = "CLOUD_FREE_DAILY_QUOTA_PAUSED"
STOP_PROVIDER_QUOTA_EXHAUSTED = "PROVIDER_QUOTA_EXHAUSTED"

DEFAULT_NORMAL_MAX_RUNTIME_SECONDS = 10800
DEFAULT_CONTINUOUS_MAX_RUNTIME_SECONDS = 43200
RUN_LOCK_FILENAME = "active_run.json"
